// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhcttgvaokqfxcidhmtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoY3R0Z3Zhb2txZnhjaWRobXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDYyMTksImV4cCI6MjA2OTgyMjIxOX0.NNS8Gn-oPEcVQASn2A9pvfpahDqeb35AuWZ0JgGhEbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});